#!/usr/bin/env ruby

# Copyright (c) 2018 Minqi Pan <pmq2001@gmail.com>
# 
# This file is part of spreadtheword, distributed under the MIT License
# For full terms see the included LICENSE file

require "bundler/setup"
require 'optparse'
require "ostruct"
require "spreadtheword"

USAGE = %Q{
Spread the Word (spreadtheword) v#{::Spreadtheword::VERSION}
Automatically generate a release-note document based on git commit messages.
Usage
  spreadtheword [PROJECT 1] [PROJECT 2]...[PROJECT N] [OPTION 1] [OPTION 2]...[OPTION N]
  If no projects were provided, the current directory would be used as the sole project directory.
  If multiple projects were provided, the git commit messages of those projects would be merged.

}.strip

projects = []
ARGV.keep_if do |x|
  if '-' == x[0]
    true
  else
    projects << x.dup
    false
  end
end

options = OpenStruct.new

outer_opts = nil

usage = lambda do |out|
  out.puts outer_opts
end

OptionParser.new do |opts|
  opts.banner = USAGE

  opts.on("-v", "--version", "Prints the version of rubyc and exit") do
    puts ::Spreadtheword::VERSION
    exit 0
  end

  opts.on("-h", "--help", "Prints this help and exit") do
    usage.call(STDOUT)
    STDOUT.puts
    exit 0
  end

  opts.on("--since=TAG/COMMIT-SHA1", 'Specifies the begining from which the git commits will be fetched. Default: the first commit') do |x|
    options.since = x
  end

  opts.on("--title=STRING", 'Specifies the title of the output document. Default: "Relase Notes"') do |x|
    options.title = x
  end

  opts.on("--author=STRING", "Specifies the author of the output document. Default: user.name of git config") do |x|
    options.author = x
  end

  opts.on("--wrike-id=STRING", "Specifies the OAuth Client ID of your Wrike API app.") do |x|
    options.wrikeId = x
  end

  opts.on("--wrike-token=STRING", "Specifies the access token of your Wrike API app.") do |x|
    options.wrikeToken = x
  end

  outer_opts = opts
end.parse!

instance = ::Spreadtheword.new projects, options
instance.run!
